name: delivery_customer
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  web_socket_channel: ^1.1.0
  google_maps_flutter: ^0.5.28+1
  google_maps_flutter_web: ^0.1.0
  functional_widget_annotation: ^0.5.1
  flutter_hooks: ^0.12.0
  built_value: ^7.1.0
  geolocator: ^5.3.2+2
  url_launcher: ^5.5.0
  dio: ^3.0.9
  rxdart: ^0.24.1
  firebase_messaging: ^6.0.16
  sliding_up_panel: ^1.0.2
  flutter:
    sdk: flutter
  openapi:
    path: openapi

dev_dependencies:
  build_runner: ^1.10.1
  built_value_generator: ^7.1.0
  functional_widget: ^0.7.2

flutter:
  uses-material-design: true